force ruby platform for bundle
Due to update in nokogiri, builds need to force compile on linux
to be compatible with older glibc environments.

```
ERROR: It looks like you're trying to use Nokogiri as a precompiled native gem on a system with glibc < 2.17
```